# Generated by Django 5.0.5 on 2024-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, help_text='Для подтверждения изменения необходимо пройти по ссылке, направленной на email', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
