# Generated by Django 4.2 on 2024-06-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, help_text='Для подтверждения изменения почты необходимо пройти по ссылке, направленной на email', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
